# Week 2 Day 2

### Libraries
Today we'll be talking about libraries and how to use them. 

First of all, what is a <i>library</i>? A library is simply a collection of functions that others have written, tested, and likely optimized for everyone to use. While some coding languages require you to pay for these libraries, Python is <i>open-source</i> meaning anyone can contribute and no one pays.

Two important libraries we will need today should be built in: numpy and math. To use a library, we need to <i>import</i> the library from our Anaconda download into this notebook:

In [1]:
!pip install numpy

In [2]:
import math
import numpy

<u>Important:</u> If you ever find that you do not have a library downloaded, you can install it by running this in your notebook: `!pip install library_name`. Just like the functions we design, all the functions in these libraries are typically dependent on other libraries or base code called <i>dependencies</i>. When using `pip install`, your system will typically download/update these as well to match whatever version of the library you are downloading. 

To use libraries, we have to write `library_we_want.function_we_want()`. Since we might end up writing the same library name hundreds of times, we can assign a variable to the name of the library when we import if we want to:

In [3]:
import numpy as np

Every library comes with an instruction manual called <i>documentation</i> that allows you to find what is required to run a specific library's function. For example, here is numpy's and math's: https://numpy.org/doc/ and https://docs.python.org/3/library/math.html . You should always try referring to the documentation for troubleshooting.

If you forget what the function name is in whatever library you are looking at, `dir()` will list out all of them for you:

In [4]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

### Numpy
Numpy is one of the most crucial libraries when doing mathematical computing. The reason numpy is so useful is its computational efficiency in most regards.

Numpy introduces a different type of object to the list of Python objects we know now: the numpy array. Similar to a list, a numpy array is a collection of objects. However, unlike a list, applying a function to a numpy array applies the function immediately to the elements.

In [5]:
contlist = [1, 1, 4, 5, 2, 6] # a list
contarray = np.array(contlist) # the numpy array version
type(contlist), type(contarray)

(list, numpy.ndarray)

In [6]:
contlist[0]

1

The only restriction on numpy array elements are that they are all the <u>same type of object</u>. If not, then numpy will often make them the same type.

In [7]:
np.array([1, '1'])

array(['1', '1'], dtype='<U21')

So, how do we work with numpy arrays? The way we would work with numbers (not lists).

In [8]:
4 * contlist + [1]

[1, 1, 4, 5, 2, 6, 1, 1, 4, 5, 2, 6, 1, 1, 4, 5, 2, 6, 1, 1, 4, 5, 2, 6, 1]

In [9]:
contarray

array([1, 1, 4, 5, 2, 6])

In [10]:
4 * contarray + 1

array([ 5,  5, 17, 21,  9, 25])

We also get a speed up when inputting functions:

In [11]:
n = 100000
x = np.linspace(0, 2*np.pi, n)

In [12]:
x

array([0.00000000e+00, 6.28324814e-05, 1.25664963e-04, ...,
       6.28305964e+00, 6.28312247e+00, 6.28318531e+00], shape=(100000,))

In [13]:
# using list indexing
%timeit y = [math.sin(x[i]) + math.exp(x[i]**2) for i in range(n)]

# using numpy ufuncs
%timeit y = np.sin(x) + np.exp(x**2)

99 ms ± 12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


4.01 ms ± 189 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


The reason for this speed up is called <i> vectorization </i>. Numpy functions that act on arrays (called <i> universal functions </i> or <i> ufuncs</i>) are designed to execute a single instruction on an entire data set using hardware instructions giving a dramatic speed up in most scenarios.

We can design functions so that they benefit from this same speed up as well. That is, we can <i>vectorize</i> a function:

In [14]:
def f(n):
    return math.sin(n) + math.exp(n**2)

In [15]:
x

array([0.00000000e+00, 6.28324814e-05, 1.25664963e-04, ...,
       6.28305964e+00, 6.28312247e+00, 6.28318531e+00], shape=(100000,))

In [16]:
# method 1


vectf = map(f, x) # for each element in a vector x, apply f

In [17]:
# method 2


g = np.vectorize(f)

In [18]:
%timeit out = list(map(f,x))

%timeit out = g(x)

%timeit out = np.sin(x) + np.exp(x**2)

77.1 ms ± 3.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


68.6 ms ± 5.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


3.42 ms ± 309 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Not only will numpy arrays speed up our computation for basic problems, but numpy arrays will be our matrix objects in the linear algebra section of this class:

In [19]:
contlist = np.array([1,2,3,4])
matrix = contlist.reshape(2,2)

In [20]:
matrix * matrix # element-wise multiplication

array([[ 1,  4],
       [ 9, 16]])

In [21]:
matrix @ matrix # regular matrix multiplication

array([[ 7, 10],
       [15, 22]])