# Working with Libraries
Today we'll be talking about libraries and how to use them. 

First of all, what is a <i>library</i>? A library is simply a collection of functions that others have written, tested, and (likely) optimized for everyone to use. While some coding languages require you to pay for these libraries, Python is <i>open-source</i> meaning anyone can contribute and no one pays.

Two important libraries we will need today should be built in: `numpy` and `math`. To have access to a library, we need to <i>install</i> the library to our system. For example, with `numpy`,

In [1]:
!pip install numpy

To use a library, we need to <i>import</i> the library into the notebook we are currently using,

In [2]:
import math
import numpy

<u>Important:</u> If you ever find that you do not have a library downloaded, you can try installing it by running this in your notebook: `!pip install library_name`. Just like the functions we design, all the functions in these libraries are typically dependent on other libraries or base code called <i>dependencies</i>. When using `!pip install`, your system will typically download and/or update these as well to match whatever version of the library you are downloading. 

To use libraries, we typically have to write `library_we_want.function_we_want()`. Since we might end up writing the same library name hundreds of times, we can assign a variable to the name of the library when we import if we want to:

In [3]:
import numpy as np

Every library comes with an instruction manual called <i>documentation</i> that allows you to find what is required to run a specific library's function. For example, here is `numpy`'s and `math`'s: https://numpy.org/doc/ and https://docs.python.org/3/library/math.html . You should always try referring to the documentation for troubleshooting.

If you forget what the function name is in whatever library you are looking at, `dir()` will list out all of them for you:

In [4]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

### Numpy
Numpy is one of the most crucial libraries when doing mathematical computing. The reason numpy is so useful is its computational efficiency in most regards.

Numpy introduces a different type of object to the list of Python objects we know now: the numpy array. Similar to a list, a numpy array is a collection of objects. However, unlike a list, applying a function to a numpy array applies the function immediately to the elements.

In [5]:
contlist = [1, 1, 4, 5, 2, 6] # a list
contarray = np.array(contlist) # the numpy array version
type(contlist), type(contarray)

(list, numpy.ndarray)

In [6]:
contlist[0]

1

The only restriction on numpy array elements are that they are all the <u>same type of object</u>. If not, then numpy will often make them the same type.

In [7]:
np.array([1, '1'])

array(['1', '1'], dtype='<U21')

So, how do we work with numpy arrays? The way we would work with numbers (not lists).

In [8]:
4 * contlist + [1]

[1, 1, 4, 5, 2, 6, 1, 1, 4, 5, 2, 6, 1, 1, 4, 5, 2, 6, 1, 1, 4, 5, 2, 6, 1]

In [9]:
contarray

array([1, 1, 4, 5, 2, 6])

In [10]:
4 * contarray + 1

array([ 5,  5, 17, 21,  9, 25])

We also get a speed up when inputting functions:

In [11]:
n = 100000
x = np.linspace(0, 2*np.pi, n)

In [12]:
x

array([0.00000000e+00, 6.28324814e-05, 1.25664963e-04, ...,
       6.28305964e+00, 6.28312247e+00, 6.28318531e+00], shape=(100000,))

In [13]:
# using list indexing
%timeit y = [math.sin(x[i]) + math.exp(x[i]**2) for i in range(n)]

# using numpy ufuncs
%timeit y = np.sin(x) + np.exp(x**2)

75.1 ms ± 1.78 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


1.88 ms ± 70.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


The reason for this speed up is called <i> vectorization </i>. Numpy functions that act on arrays (called <i> universal functions </i> or <i> ufuncs</i>) are designed to execute a single instruction on an entire data set using hardware instructions giving a dramatic speed up in most scenarios.

We can design functions so that they benefit from this same speed up as well. That is, we can <i>vectorize</i> a function:

In [14]:
def f(n):
    return math.sin(n) + math.exp(n**2)

In [15]:
x

array([0.00000000e+00, 6.28324814e-05, 1.25664963e-04, ...,
       6.28305964e+00, 6.28312247e+00, 6.28318531e+00], shape=(100000,))

In [16]:
# method 1


vectf = map(f, x) # for each element in a vector x, apply f

In [17]:
# method 2


g = np.vectorize(f)

In [18]:
%timeit out = list(map(f,x))

%timeit out = g(x)

%timeit out = np.sin(x) + np.exp(x**2)

58.3 ms ± 1.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


56.3 ms ± 511 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


1.82 ms ± 5.01 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Not only will numpy arrays speed up our computation for basic problems, but numpy arrays will be our matrix objects in the linear algebra section of this class:

In [19]:
contlist = np.array([1,2,3,4])
matrix = contlist.reshape(2,2)

In [20]:
matrix * matrix # element-wise multiplication

array([[ 1,  4],
       [ 9, 16]])

In [21]:
matrix @ matrix # regular matrix multiplication

array([[ 7, 10],
       [15, 22]])

### Practice Lab Problems
1. 

If not already installed, install the numpy library using `!pip install numpy`. After installing, import numpy with variable name `np`.

---

2. 

We will use other libraries throughout this semester as well. Here are a couple:

- `matplotlib`
- `networkx`
- `pandas`
- `geopandas`

Try importing these libraries. If they are not installed, use `pip install` to install them for future use.

---

3. 

Given

```python
a = np.array([2, 4, 6, 8])
```

compute each of the following:

- `a + 3`
- `2 * a`
- `a**2`
- `a - 1`

Do not use a `for` loop.

---

4. 

The derivative of a function \(f(x)\) at a point \(x\) is defined as the limit

$f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}$

provided the limit exists.

Define a function $g(h)$ that computes the quotient above for a given function $f$ near a point $x$. Then, vectorize $g$. 


Using `np.linspace()`, let $f(x)=sin(x)$ and compute $g$ at $10^{-1}, 10^{-2}, 10^{-3}, 10^{-4}$. This will be an estimate for the derivative of $f$. Compare to the actual derivative.

---

5. 
Let

$$A=\begin{bmatrix}
2 & 1 \\
3 & 4
\end{bmatrix}~~~~ B= \begin{bmatrix}
5 & 2 \\
1 & 6
\end{bmatrix}$$

Compute the product.

### Lab Key*
1. 

In [22]:
!pip install numpy

In [23]:
import numpy as np

2. 

In [24]:
!pip install matplotlib
!pip install networkx
!pip install pandas
!pip install geopandas

  Using cached pandas-3.0.5-cp311-cp311-win_amd64.whl.metadata (19 kB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/10.0 MB 2.1 MB/s eta 0:00:05
   ---- ----------------------------------- 1.0/10.0 MB 1.6 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/10.0 MB 1.6 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/10.0 MB 1.6 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/10.0 MB 1.0 MB/s eta 0:00:09
   ----- ---------------------------------- 1.3/10.0 MB 1.0 MB/s eta 0:00:09
   ------ --------------------------------- 1.6/10.0 MB 942.3 kB/s eta 0:00:09
   ------ --------------------------------- 1.6/10.0 MB 942.3 kB/s eta 0:00:09
   ------- -------------------------------- 1.8/10.0 MB 875.3 kB/s eta 0:00:10
   -------- ------------------------------- 2.1/10.0 MB 870.1 kB/s eta 0:00:10
   --------

^C
  Using cached geopandas-1.1.4-py3-none-any.whl.metadata (2.3 kB)
  Using cached pyogrio-0.13.0-cp311-abi3-win_amd64.whl.metadata (6.0 kB)
  Using cached pyproj-3.7.2-cp311-cp311-win_amd64.whl.metadata (31 kB)


3. 

In [ ]:
a = np.array([2, 4, 6, 8])
print(a+3)
print(2*a)
print(a**2)
print(a-1)

4. 

In [ ]:
import math

In [ ]:
x = np.pi # some point x

def g(h):                  
    return (f(x+h)-f(x))/h  # quotient for derivative

G = np.vectorize(g)   # vectorize g
def f(x):
    return math.sin(x) # f of choice

h = np.linspace(-1, -4, 4)   # -1, -2, -3, -4
h = 10**h                   # 10^-1, 10^-2, 10^-3, 10^-4

print(G(h))                 # evalutate the vectorized version of g at h values
print(math.cos(np.pi))      # actual derivative

5. 


In [ ]:
a = [2,1,3,4]
b = [5,2,1,6]
A = np.array(a).reshape(2,2)
B = np.array(b).reshape(2,2)
A @ B