# Week 2 Day Lab

### Problem 1: Installing NumPy

If not already installed, install the numpy library using `!pip install numpy`. After installing, import numpy with variable name `np`.

In [1]:
!pip install numpy

In [2]:
import numpy as np

### Problem 2: Installing other libraries
We will use other libraries throughout this semester as well. Here are a couple:

    - matplotlib
    - networkx
    - pandas
    - geopandas
Try importing these libraries. If they are not installed, use `pip install` to install them for future use.

In [3]:
!pip install matplotlib

^C


  Using cached contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.3 MB 5.6 MB/s eta 0:00:02
   --------- ------------------------------ 2.1/9.3 MB 5.6 MB/s eta 0:00:02
   -------------- ------------------------- 3.4/9.3 MB 5.9 MB/s eta 0:00:01
   -------------------- ------------------- 4.7/9.3 MB 5.8 MB/s eta 0:00:01
   ------------------------ --------------- 5.8/9.3 MB 5.7 MB/s eta 0:00:01
   ----------------------------- ---------- 6.8/9.3 MB 5.8 MB/s eta 0:00:01
   ------------------------------------ --- 8.4/9.3 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 5.7 MB/s  0:00:01
Using cached contourpy-1.3.3-cp311-cp311-win_amd64.whl (225 kB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------- ----------------- 1.3/2.4 

In [ ]:
!pip install networkx

In [ ]:
!pip install pandas

In [ ]:
!pip install geopandas

### Problem 3

Given

```python
a = np.array([2, 4, 6, 8])
```

compute each of the following:

1. a + 3
2. 2 * a
3. a**2
4. a - 1

Do not use a `for` loop.


In [3]:
a = np.array([2, 4, 6, 8])
print(a+3)
print(2*a)
print(a**2)
print(a-1)

[ 5  7  9 11]
[ 4  8 12 16]
[ 4 16 36 64]
[1 3 5 7]


### Problem 4

The derivative of a function \(f(x)\) at a point \(x\) is defined as the limit

$
f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}
$

provided the limit exists.

Define a function $g(h)$ that computes the quotient above for a given function $f$ near a point $x$. Then, vectorize $g$. 


Using `np.linspace()`, let $f(x)=sin(x)$ and compute $g$ at $10^{-1}, 10^{-2}, 10^{-3}, 10^{-4}$. This will be an estimate for the derivative of $f$. Compare to the actual derivative.

In [4]:
import math

In [30]:
x = np.pi # some point x

def g(h):                  
    return (f(x+h)-f(x))/h  # quotient for derivative

G = np.vectorize(g)   # vectorize g
def f(x):
    return math.sin(x) # f of choice

h = np.linspace(-1, -4, 4)   # -1, -2, -3, -4
h = 10**h                   # 10^-1, 10^-2, 10^-3, 10^-4

print(G(h))                 # evalutate the vectorized version of g at h values
print(math.cos(np.pi))      # actual derivative

[-0.99833417 -0.99998333 -0.99999983 -1.        ]
-1.0


###  Problem 5
Let

$
A=
\begin{bmatrix}
2 & 1 \\
3 & 4
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
5 & 2 \\
1 & 6
\end{bmatrix}
$

Compute the product.

In [28]:
a = [2,1,3,4]
b = [5,2,1,6]
A = np.array(a).reshape(2,2)
B = np.array(b).reshape(2,2)

In [35]:
A @ B

array([[11, 10],
       [19, 30]])