# `numpy` Matrix Basix
This week we are going to focus on linear algebra and optimization methods in Python. Today, we'll re-introduce matrices.

In [2]:
# preliminaries

import numpy as np

### Vectors
Recalling your experiences in Math 220, we typically start linear algebra with vector operations. In Python, typically, vectors are one-dimensional numpy arrays:

In [6]:
x = np.array([1,2,3,4])
y = np.array([-1,0,2,0])

In [7]:
x

array([1, 2, 3, 4])

In [9]:
print(x + y)
print(x - y)

[0 2 5 4]
[2 2 1 4]


Remember why numpy arrays are so nice: they act like numbers! We can add/subtract vectors:

We can scale vectors:

In [10]:
2 * x

array([2, 4, 6, 8])

We can also take the dot product of vectors:

In [11]:
print(np.dot(x, y))
print(x @ y)

5
5


In [12]:
np.outer(x,y)

array([[-1,  0,  2,  0],
       [-2,  0,  4,  0],
       [-3,  0,  6,  0],
       [-4,  0,  8,  0]])

The norm a vector can be easily computed so that we can normalize:

In [15]:
norm = np.linalg.norm(x)

normalizedx = x/norm

print(norm)
print(normalizedx)
print(np.linalg.norm(normalizedx))

5.477225575051661
[0.18257419 0.36514837 0.54772256 0.73029674]
0.9999999999999999


### Matrices
We can likewise perform operations on matrices!

To define a matrix, we can do two things:

In [18]:
A = np.array([[1,2],
              [3,4]])

B = np.array([1,2,3,4]).reshape(2,2)

print(A)
print(B)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


If you need to know a matrix's size, simply use the `.shape` attribute:

In [19]:
A.shape

(2, 2)

Still, these are numpy arrays. Basic operations work exactly as we would like:

In [20]:
print(A + B)
print(3 * A)

[[2 4]
 [6 8]]
[[ 3  6]
 [ 9 12]]


To perform matrix multiplication, we simply use `np.dot()` or `@`:

In [21]:
print(np.dot(A, B))
print(A @ B)

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [22]:
print(A*B) # elementwise multiplication

[[ 1  4]
 [ 9 16]]


We can compute the transpose in a couple ways:

In [23]:
print(A.T )
print(np.transpose(A))

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


For the typical properties of matrices we like, numpy has them built in!

In [25]:
# inverse

print(np.linalg.inv(A))

# determinant

print(np.linalg.det(A))

# rank

print(np.linalg.matrix_rank(A))

# trace

print(np.trace(A))

# eigenvalues/eigenvectors

print(np.linalg.eig(A))

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
2
5
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [29]:
np.linalg.eig(A)[1]

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

### Lab Problems

---

1.
Write your own function performs vectors addition on lists instead of arrays.

---

2.
Create two $3\times 2$ matrices, A and B. Compute: 
- A+B
- AB

---

3.
Make a 2 by 2 invertible matrix, A.
- Compute its eigenvectors and plot them using matplotlib
- Compute A times the eigenvectors and plot them on the same plot.
- What do you notice?

---

4.
Write your own function that creates a random 3 by 3 matrix using `np.random` for the entries.

### Lab Key*

---

1. 

---

2.

---

3.

---

4.